# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-26 12:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='MealPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal_plan', models.CharField(choices=[('sunm', 'Sunday Meal'), ('satm', 'Saturday Meal')], db_index=True, max_length=100)),
                ('meal_price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Retreat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('slug', models.SlugField(blank=True, max_length=250, null=True)),
                ('description', models.TextField()),
                ('retreat_datetime', models.DateTimeField(db_index=True)),
                ('recurring_datetime', models.DateTimeField(db_index=True)),
            ],
        ),
    ]
