# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-26 12:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rrs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=100)),
                ('slug', models.SlugField(blank=True, max_length=250, null=True)),
                ('session_type', models.CharField(choices=[('faculty', 'Faculty'), ('staff', 'Staff'), ('age_group', 'Age Group')], max_length=10)),
                ('retreat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retreat_sessions', to='rrs.Retreat')),
            ],
        ),
    ]
