# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-26 12:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rrs', '0002_session'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('official_name', models.CharField(db_index=True, max_length=100)),
                ('badge_name', models.CharField(db_index=True, max_length=100)),
                ('age', models.PositiveIntegerField()),
                ('telephone', models.CharField(blank=True, max_length=30, null=True)),
                ('gender', models.CharField(choices=[('m', 'Male'), ('f', 'Femail')], max_length=2)),
                ('job_type', models.CharField(choices=[('faculty', 'Faculty'), ('staff', 'Staff')], max_length=10)),
                ('department', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='department_attendees', to='rrs.Department')),
            ],
        ),
        migrations.RenameField(
            model_name='mealplan',
            old_name='meal_plan',
            new_name='plan_name',
        ),
        migrations.AddField(
            model_name='attendee',
            name='meal_plan',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='meal_plan', to='rrs.MealPlan'),
        ),
        migrations.AddField(
            model_name='attendee',
            name='session',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='session_attendees', to='rrs.Session'),
        ),
    ]
