# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-26 12:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rrs', '0003_auto_20170426_1219'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dependent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('gender', models.CharField(choices=[('m', 'Male'), ('f', 'Femail')], db_index=True, max_length=2)),
                ('attendee', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='dependents', to='rrs.Attendee')),
            ],
        ),
    ]
