# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-26 13:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rrs', '0006_auto_20170426_1308'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendee',
            name='badge_name',
        ),
    ]
