# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-26 13:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rrs', '0007_remove_attendee_badge_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendee',
            name='gender',
            field=models.CharField(choices=[('m', 'Male'), ('f', 'Female')], db_index=True, max_length=2),
        ),
        migrations.AlterField(
            model_name='dependent',
            name='gender',
            field=models.CharField(choices=[('m', 'Male'), ('f', 'Female')], db_index=True, max_length=2),
        ),
    ]
