# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-26 14:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rrs', '0009_auto_20170426_1344'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionChair',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rrs.Attendee')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_chairs', to='rrs.Session')),
            ],
        ),
    ]
