# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-26 14:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rrs', '0010_sessionchair'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mealplan',
            name='plan_name',
            field=models.CharField(choices=[('sunday_meal', 'Sunday Meal'), ('saturday_meal', 'Saturday Meal')], db_index=True, max_length=100),
        ),
    ]
