# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-26 19:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rrs', '0015_auto_20170426_1748'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sessionchair',
            old_name='session',
            new_name='chair',
        ),
    ]
